### ISSUE TITLE
Размещение окон скрипта по центру экрана

### ISSUE THREAD

**Issue by imasuridondai** [SthephanShinkufag/Dollchan-Extension-Tools#1191]
Вот есть CSS-трюк для размещения панели скрипта не справа, а по центру. Но окна скрипта («Избранное», «Скрытое» и т.д.) при его использовании всё равно остаются справа. Можно как-нибудь и их по центру разместить?

**Comment by SthephanShinkufag** [comment]
Надо подумать. Вечером отпишусь.

**Comment by SthephanShinkufag** [comment]
Пожалуйста:

```css
.de-win-fixed { right: 50% !important; transform: translateX(50.5%); }
```

Добавил на страничку с СSS-трюками.
