### ISSUE TITLE
харкач - сломался зум картинок

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1212]
Проще показать, вот видео с демонстрацией бага:
https://transfer.sh/Cf6te/2018_04_06_16_57_18_551.mp4 - перезалил

**Comment by NEONZARIN** [comment]
Это было на других бордах ранее. Я думал это фича такая.

**Comment by Y0ba** [comment]
Это скорее всего стиль ставит анимации на лишние элементы. Попробуй применить CSS:
```css
.de-fullimg-center, .de-fullimg-wrap-link, .de-fullimg-wrap, .de-fullimg, .de-fullimg-info {
    -webkit-transition: none !important;
    -moz-transition: none !important;
    transition: none !important;
}
```
