### ISSUE TITLE
Странный баг в /po

### ISSUE THREAD

**Issue by solara322** [SthephanShinkufag/Dollchan-Extension-Tools#1260]
Оп посты почему то частично написаны задом наперёд.
https://ibb.co/dLXDey
https://ibb.co/fb9FsJ
https://ibb.co/g9W6zy

**Comment by Y0ba** [comment]
Фокус в том, чтобы в тему добавить символ [`RIGHT-TO-LEFT OVERRIDE`](http://www.fileformat.info/info/unicode/char/202e/index.htm)

Можно добавить в CSS:
```css
.post-title { display: inline-block !important; }
```

Тогда символ будет действовать не на весь заголовок поста, а только на тему.
