### ISSUE TITLE
Can't copy video url while clicking on the video

### ISSUE THREAD

**Issue by codebully** [SthephanShinkufag/Dollchan-Extension-Tools#1290]
I was pushed to update and then somehow it became this: https://files.catbox.moe/z7fg9l.mp4

Before you fucked up it was actually usable, what happened there man?

Can you maybe revert that to the state where the video had a top border with a close button and could normally be moved?

**Comment by SthephanShinkufag** [comment]
> you fucked up

Say it to mozilla developers.

> Can you

No.

Click over the bottom control panel, and context menu will work.
Or use [custom CSS](https://github.com/sthephanshinkufag/dollchan-extension-tools/wiki/css-tricks-en):

> Firefox Quantum: how to drag webm by header? How to close webm by a cross icon? How to pause webm by left-click in any area?

> Open the `"Settings"` `(Alt+S)` > `"Common"`, enable `"User CSS"` and press `"Edit"`, paste the desired code and click `"Save"`.

```css
.de-fullimg-center-video { border-top: 20px solid #444 !important; border-radius: 10px 10px 0 0; cursor: pointer; }
.de-fullimg-center-video > .de-fullimg-video::before { right: 6px !important; top: -20px; }
.de-fullimg-video::before { content: "\2716"; color: #fff; background-color: rgba(64, 64, 64, 0.8); text-align: center; width: 20px; height: 20px; position: absolute; right: 0; font: bold 14px/18px tahoma; cursor: pointer; }
.de-fullimg-video-hack { display: none; }
```
