### ISSUE TITLE
CSS макабы

### ISSUE THREAD

**Issue by Y0ba** [SthephanShinkufag/Dollchan-Extension-Tools#1308]
На абучане у постов появились три точки рядом с постами и из-за особенностей CSS куклы, теперь они отображаются на всех служебных элементах, включая табы в настройках, менюшки и превью. Наиболее универсальный селектор для отключения такой:
```css
.post:not(.de-reply)::before { display: none !important; }
```
Думаю стоит добавить в CSS для макабы.
