### ISSUE TITLE
Кнопки постов (косметика)

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#854]
Раньше, чтобы между сабжем и их меню был отступ в 1px, я добавлял кнопкам `border-bottom: 1px solid transparent;`. Однако теперь это почему-то перестало работать и меню выводится вплотную, хотя атрибут действует (видно хотя бы по изменению вертикального положения кнопок). В чём причина и как пофиксить?

Вообще предлагаю сделать так изначально - красивее и "чище" выглядит, да и смещённые на 1px вверх кнопки тогда выровнены по центру текстовой строки, а не по её верхней границе, свисая вниз, что имхо хуже смотрится.

**Comment by Y0ba** [comment]
> Раньше, чтобы между сабжем и их меню был отступ в 1px

Добавил отступ в код.

> Вообще предлагаю сделать так изначально

Что именно? Покажи результат.

**Comment by VisualKei** [comment]
Да, так отлично, спасибо.
А про вертикальное смещение - сделать кнопкам вместо `margin: 0 4px -2px 0` — `margin: 0 4px -1px 0`, и посткаунтерам вместо `vertical-align: 1px;` — `vertical-align: 2px;`
Сейчас:
![bad](https://cloud.githubusercontent.com/assets/1483359/10729493/cea75c66-7bfa-11e5-8a5b-e9100866c314.png)
Лучше:
![good](https://cloud.githubusercontent.com/assets/1483359/10729501/df4efd9e-7bfa-11e5-9ca5-0bd2cc0501a9.png)

**Comment by SthephanShinkufag** [comment]
Отстой. не знаю, какой у тебя глазомер, но кнопки у будут явно выше, чем по центру текста.
Сейчас все ровно.

**Comment by SthephanShinkufag** [comment]
Хотя, если настроить глаз и восприятие по выравниванию снизу, тогда может быть. Но вы учтите, что шрифт может быть мельче, чем на ычане. Тогда кнопки будут торчать кверху очень ощутимо.

**Comment by Y0ba** [comment]
Вообще степан прав лучше меню пусть будет вплотную. А то даже несмотря на задержку исчезания некоторые слоупоки не будут успевать. Вот работающий CSS код для увелячения расстояния:
```css
.de-menu { margin: 1px 0 !important; }
```

**Comment by Y0ba** [comment]
В последнем коммите добавил дополнительные классы. Вот так теперь лучше всего:
```css
.de-menu-down { margin: 1px 0 0 0 !important; }
```

**Comment by VisualKei** [comment]
>Хотя, если настроить глаз и восприятие по выравниванию снизу, тогда может быть.

Ну да, из этого и исхожу - снизу текст выровнен по базовой линии, а сверху буквы разной высоты. Но это дело вкуса, поправлю у себя.

>меню будет пропадать при перемещении по пустоте

Ну вот именно поэтому я прозрачной рамкой и делал. Почему это перестало работать?

**Comment by SthephanShinkufag** [comment]
> Почему это перестало работать?

Тому що <svg> довольно специфический элемент. Там много чего не работает.

**Comment by VisualKei** [comment]
А напомните, в чём профит от svg?

**Comment by Y0ba** [comment]
Вектор же.

**Comment by SthephanShinkufag** [comment]
Такое-то няшное масштабирование! Прозумь страницу, и то офигеешь от четкости кнопки, никакого мыла. Ну, и возможность кастомизации кнопок вплоть до отдельных элементов рисунка.

**Comment by Y0ba** [comment]
У меня `border` вполне себе работает. Только надо изменить метод расчёта размера элементов, а то браузер уменьшает размер кнопки если установлен `box-sizing: border-box;`.

```css
.de-btn-expthr, .de-btn-fav, .de-btn-fav-sel, .de-btn-hide, .de-btn-hide-user, .de-btn-unhide, .de-btn-unhide-user, .de-btn-rep, .de-btn-sage, .de-btn-src, .de-btn-stick, .de-btn-stick-on {
    border-bottom: 1px solid transparent;
    box-sizing: content-box;
}
```
