### ISSUE TITLE
Уведомление в фавикон

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#886]
Я так понимаю, зеленый плюсик - ответ на мои посты, желтый - просто новые?
Так вот, иногда глючит. Выдает зеленый, хотя ответ не на мой пост.

А на макабе линк на мои посты, помечающийся как "You" - это же фишка куклы? Т.е. все номера постов хранятся в локалсторадж?

**Comment by SthephanShinkufag** [comment]
> А на макабе линк на мои посты, помечающийся как "You" - это же фишка куклы? Т.е. все номера постов хранятся в локалсторадж?

Да.

**Comment by YellowSM** [comment]
А отключать это нельзя? Палево жи. Да и ресурсы лишние жрет.

**Comment by Y0ba** [comment]
> Палево жи.

Для этого придумали приватный режим. Есть во всех современных браузерах. Алсо, можно отключить при помощи CSS: 
```css
.de-ref-my::after { content: none; }
.de-ref-del.de-ref-my::after { content: " (Del)"; }\
.de-ref-op.de-ref-my::after { content: " (OP)"; }\
```

> Да и ресурсы лишние жрет.

Разве что оперативку, да и то очень мало.
