### ISSUE TITLE
CSS не работает только на форчане

### ISSUE THREAD

**Issue by UserNaem** [SthephanShinkufag/Dollchan-Extension-Tools#942]
CSS:
#de-panel,
.de-win-head {
    background: none;
    background-color: #333333;
    border-radius: 0px 0px 0 0;
}
Ожидал:
Квадратные углы у всех заголовков на всех бордах (пик 1)
Получил:
Скругленные углы только у заголовка плавающей формы ответа только на форчане (пик 2)

CSS ставил через Stylish (через пользовательский CSS тоже не работает).
Firefox Developer Edition 50.0a2 (2016-08-05)
Dollchan v16.6.17.0.d3b8f7e

Пик 1
![b_-_dollchan_extension_tools_-_firefox_developer_ 15 08 16 08-26-27](https://cloud.githubusercontent.com/assets/21028464/17654239/4bfbe6b8-62ba-11e6-89eb-32b997b1a034.png)
Пик 2
![wg_-_lets_see_them _-_firefox_developer_edition 15 08 16 08-28-11](https://cloud.githubusercontent.com/assets/21028464/17654243/4e7d8716-62ba-11e6-858c-d7c2cad81a33.png)

**Comment by SthephanShinkufag** [comment]
```css
#de-panel, .de-win-head {
    background: none;
    background-color: #333333;
    border-radius: 0;
}

#de-win-reply.de-win {
    border-radius: 0;
}
```
