### ISSUE TITLE
Проблемы с кнопками разметки

### ISSUE THREAD

**Issue by swnlswnw** [SthephanShinkufag/Dollchan-Extension-Tools#990]
Мейлач обновился и теперь кнопка со стикерами налазит на кнопку "**Жирный**".  Так же некоректно отображается превью самих стикеров из-за кнопок разметки.

Версия куклы и мозилы последняя.

**Comment by SthephanShinkufag** [comment]
Пасскодопроблемы.
У меня нет псссс-кода, и нет кнопки стикера. Даже не знаю, как он выглядит.

Если есть кто-то с псссс-кодом, пусть покажет это на скриншоте вместе с html- и css- разметкой.
А еще лучше, если кто-нибудь это сам исправит, и отправит сюда пулл-реквест.
%%Псссскод не куплю.%%

**Comment by Oduvanchik7227** [comment]
Щас бы капчу вводить.

Проблема решается переносом панели с кнопками разметки наверх, вкладка "Форма" (убрать галку "Внизу").

> вместе с html- и css- разметкой
Не знаю, что для этого необходимо сделать. 

Кнопка болда недоступна - [https://s21.postimg.org/qm6pnan87/image.png](url)
После переноса панели - [https://s16.postimg.org/u15dz9arp/image.png](url)

**Comment by Y0ba** [comment]
А стикеры с куклой вообще работают?

**Comment by Y0ba** [comment]
Так-то можно добавить в CSS
```css
.message-sticker-btn, .message-sticker-preview { display: none; }
```
чтобы скрыть эту кнопку.

**Comment by SthephanShinkufag** [comment]
Йоба, пасскодовладелец?

**Comment by Y0ba** [comment]
Стикеры доступны для всех (но не все). Возможно надо почистить куки.

**Comment by SthephanShinkufag** [comment]
Вангую, к той кнопке надо какой-нибудь margin применить, да и всё.

**Comment by SthephanShinkufag** [comment]
css для кнопки:

```css
  .message-sticker-btn {
    position: static !important;
    display: inline-block;
    margin: 0 -28px 0 2px;
  }
```
